"""Final seller verification route override.

The original application already registers /verify-seller/<token>. Merely adding
another identical URL rule does not replace the earlier rule: Werkzeug dispatches
the first matching rule. This module therefore replaces the view functions of
existing matching rules and only adds a route when one does not already exist.
"""

from flask import flash, redirect, url_for
from flask_login import current_user
from itsdangerous import BadSignature, SignatureExpired

from sitefix import app
import app as app_module
import seller_verification_fix as seller_fix


def _public_store_url(slug):
    if not slug:
        raise ValueError('Seller store was not created correctly.')
    return url_for('public_store', seller_slug=slug, _external=True)


def _settings_or_login():
    return redirect(url_for('settings') if current_user.is_authenticated else url_for('login'))


def verify_seller(token):
    try:
        data = seller_fix._load_token(token)
        if data.get('purpose') not in ('seller-link', 'seller-whatsapp'):
            raise BadSignature()

        user_id = int(data['id'])
        user = app_module.User.query.filter_by(id=user_id).first()
        if not user:
            raise BadSignature()

        # A previously completed verification must never fall back to Settings.
        if user.role == 'seller' and user.seller_verified:
            seller_url = _public_store_url(user.seller_slug)
            return seller_fix._verification_progress_html(
                user.username or 'Seller',
                seller_url,
            )

        if user.role != 'buyer' or user.seller_verification_status != 'pending':
            flash('This seller verification link is no longer valid. Start Seller Mode again to create a new link.')
            return _settings_or_login()

        seller_name = (user.pending_seller_name or user.username or 'Merco Seller').strip()[:100]
        public_email = seller_fix._valid_email(user.pending_seller_email)
        phone = seller_fix._normalize_phone(user.pending_seller_phone)
        whatsapp = seller_fix._normalize_phone(user.pending_seller_whatsapp)

        if not public_email or not phone or not whatsapp:
            raise ValueError('The saved seller email or phone details are no longer valid. Please restart Seller Mode.')

        # The signed link is the verification action. The saved contact values
        # are checked again immediately before seller activation.
        slug = app_module.unique_seller_slug(seller_name, user.id)
        user.role = 'seller'
        user.username = seller_name
        user.seller_slug = slug
        user.whatsapp_number = whatsapp
        user.seller_verified = True
        user.seller_verification_status = 'verified'
        user.pending_seller_name = None
        user.pending_seller_email = None
        user.pending_seller_phone = None
        user.pending_seller_whatsapp = None
        app_module.db.session.commit()

        seller_url = _public_store_url(slug)
        app.logger.info('SELLER_VERIFICATION_SUCCESS user_id=%s slug=%s', user.id, slug)
        return seller_fix._verification_progress_html(seller_name, seller_url)

    except SignatureExpired:
        app_module.db.session.rollback()
        flash('That seller verification link has expired. Start Seller Mode again to create a new 5-minute link.')
        return _settings_or_login()
    except (BadSignature, ValueError, TypeError, KeyError):
        app_module.db.session.rollback()
        flash('That seller verification link is invalid. Start Seller Mode again to create a new link.')
        return _settings_or_login()
    except Exception:
        app_module.db.session.rollback()
        app.logger.exception('Final seller verification route failed')
        return _settings_or_login()


def _replace_or_add_rule(rule_path, endpoint, view_func):
    """Make sure an existing URL path actually dispatches to our final handler."""
    matching = [rule for rule in app.url_map.iter_rules() if rule.rule == rule_path]
    if matching:
        for rule in matching:
            app.view_functions[rule.endpoint] = view_func
        return
    app.add_url_rule(rule_path, endpoint=endpoint, view_func=view_func)


# The app already has a /verify-seller/<token> rule. Replace its registered
# endpoint rather than adding a duplicate rule that would never be reached.
_replace_or_add_rule('/verify-seller/<token>', 'verify_seller_final', verify_seller)

# Keep any old endpoint names pointing to the same final implementation.
app.view_functions['verify_seller_whatsapp'] = verify_seller
if 'verify_seller_final' not in app.view_functions:
    app.view_functions['verify_seller_final'] = verify_seller

# Also expose a separate clean compatibility URL for links generated by newer
# versions, without touching the original /verify-seller/<token> dispatch.
if not any(rule.rule == '/verify-seller-final/<token>' for rule in app.url_map.iter_rules()):
    app.add_url_rule('/verify-seller-final/<token>', endpoint='verify_seller_final_url', view_func=verify_seller)
