"""Seller verification without a WhatsApp API.

The verification URL is a short-lived signed capability. Normal WhatsApp is
only used to share the link; no WhatsApp API is required.
"""
import hashlib
import os
from urllib.parse import quote

from flask import flash, redirect, request, url_for
from flask_login import current_user
from itsdangerous import URLSafeTimedSerializer, BadSignature, SignatureExpired

import merco_runtime
from sitefix import app
import app as app_module
import bootstrap

SELLER_VERIFICATION_MAX_AGE = 300
SELLER_TOKEN_SALT = "merco-seller-whatsapp-v2"


def _seller_serializer():
    """Return a signing serializer that stays identical across Railway workers.

    The legacy app falls back to a random SECRET_KEY when SECRET_KEY is not set.
    That makes links generated by one Gunicorn worker impossible to verify in
    another worker, or after a restart. Prefer the configured SECRET_KEY; when
    it is absent, derive a stable private key from DATABASE_URL so the seller
    link still works without adding another Railway variable.
    """
    configured = (os.environ.get("SECRET_KEY") or "").strip()
    if configured:
        key = configured
    else:
        database_url = (os.environ.get("DATABASE_URL") or "").strip()
        seed = database_url or "merco-local-seller-verification"
        key = hashlib.sha256(("merco-seller-key-v1:" + seed).encode("utf-8")).hexdigest()
    return URLSafeTimedSerializer(key, salt=SELLER_TOKEN_SALT)


def _token(user):
    whatsapp = ''.join(ch for ch in (user.pending_seller_whatsapp or '') if ch.isdigit())
    return _seller_serializer().dumps({
        'id': int(user.id),
        'whatsapp': whatsapp,
        'purpose': 'seller-whatsapp',
    })


def _verification_url(user):
    base = (os.environ.get('MERCO_PUBLIC_URL') or 'https://maximise-production.up.railway.app').rstrip('/')
    return f"{base}/verify-seller-whatsapp/{_token(user)}"


def _activate_seller_fixed():
    if not current_user.is_authenticated:
        return redirect(url_for('login'))
    if current_user.role != 'buyer':
        return redirect(url_for('dashboard'))
    try:
        seller_name = (request.form.get('seller_name') or current_user.username).strip()[:100]
        public_email = (request.form.get('contact_email') or current_user.email).strip()[:160]
        phone = (request.form.get('phone_number') or '').strip()[:40]
        whatsapp = ''.join(ch for ch in (request.form.get('whatsapp') or '').strip() if ch.isdigit())[:30]
        if not seller_name or not public_email or '@' not in public_email or not phone or not whatsapp:
            raise ValueError('Seller name, public email, phone and WhatsApp are required.')
        customer_care = ''.join(ch for ch in os.environ.get('MERCO_VERIFICATION_WHATSAPP', '').strip() if ch.isdigit())
        if not customer_care:
            raise ValueError('Seller verification is temporarily unavailable. Please contact Merco support.')

        bootstrap.save_contact(current_user, public_email, phone, require_phone=True)
        current_user.pending_seller_name = seller_name
        current_user.pending_seller_email = public_email
        current_user.pending_seller_phone = phone
        current_user.pending_seller_whatsapp = whatsapp
        current_user.seller_verification_status = 'pending'
        current_user.seller_verified = False
        app_module.db.session.commit()

        verification_link = _verification_url(current_user)
        message = (
            'Hello Merco Customer Care, I want to open a seller store.\n\n'
            f'Name: {seller_name}\n'
            f'WhatsApp: {whatsapp}\n\n'
            'My secure seller verification link is below. I will open it within 5 minutes to activate Seller Mode automatically.\n\n'
            f'Verification link: {verification_link}'
        )
        wa_url = f'https://wa.me/{customer_care}?text={quote(message, safe="")}'
        flash('WhatsApp is ready with your secure verification link. Send the message, then open the link within 5 minutes to activate your store.')
        return redirect(wa_url)
    except ValueError as exc:
        app_module.db.session.rollback()
        flash(str(exc))
        return redirect(url_for('settings'))
    except Exception:
        app_module.db.session.rollback()
        app.logger.exception('Seller verification request failed')
        flash('Seller verification could not be started. Please try again.')
        return redirect(url_for('settings'))


def _verify_seller_whatsapp_fixed(token):
    """Verify the seller request without WhatsApp API, email, or admin approval."""
    try:
        if not token:
            raise BadSignature()

        # Use the stable seller serializer rather than the legacy app serializer.
        # This is critical when Railway runs multiple workers or restarts the app.
        data = _seller_serializer().loads(token, max_age=SELLER_VERIFICATION_MAX_AGE)
        if data.get('purpose') != 'seller-whatsapp':
            raise BadSignature()

        user_id = int(data['id'])
        token_whatsapp = ''.join(ch for ch in str(data.get('whatsapp') or '') if ch.isdigit())
        if not token_whatsapp:
            raise BadSignature()

        user = app_module.User.query.filter_by(id=user_id).first()
        if not user:
            raise BadSignature()

        stored_whatsapp = ''.join(ch for ch in (user.pending_seller_whatsapp or '') if ch.isdigit())
        if (
            user.role != 'buyer'
            or user.seller_verification_status != 'pending'
            or not stored_whatsapp
            or stored_whatsapp != token_whatsapp
        ):
            flash('This seller verification link is no longer valid. Start Seller Mode again to get a new link.')
            return redirect(url_for('settings') if current_user.is_authenticated else url_for('login'))

        seller_name = (user.pending_seller_name or user.username or 'Merco Seller').strip()[:100]
        slug = app_module.unique_seller_slug(seller_name, user.id)

        user.role = 'seller'
        user.username = seller_name
        user.seller_slug = slug
        user.whatsapp_number = user.pending_seller_whatsapp
        user.seller_verified = True
        user.seller_verification_status = 'verified'
        user.pending_seller_name = None
        user.pending_seller_email = None
        user.pending_seller_phone = None
        user.pending_seller_whatsapp = None
        app_module.db.session.commit()

        if current_user.is_authenticated and current_user.id == user.id:
            flash('Seller verification successful. Your store is now active.')
            return redirect(url_for('seller_dashboard'))

        return redirect(url_for('seller_verification_success'))

    except (BadSignature, SignatureExpired, ValueError, TypeError, KeyError):
        flash('That seller verification link is invalid or has expired. Start Seller Mode again to get a new link.')
        return redirect(url_for('settings') if current_user.is_authenticated else url_for('login'))
    except Exception:
        app_module.db.session.rollback()
        app.logger.exception('Seller verification failed')
        flash('Seller verification could not be completed. Please request a new link.')
        return redirect(url_for('settings') if current_user.is_authenticated else url_for('login'))


def _seller_verification_success():
    return (
        '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1">'
        '<title>Seller verified · Merco</title></head>'
        '<body style="margin:0;min-height:100vh;display:grid;place-items:center;background:#050a08;color:#e0f2f1;font-family:Arial,sans-serif">'
        '<main style="max-width:520px;margin:24px;padding:32px;border:1px solid rgba(0,255,136,.28);border-radius:22px;background:#0a1912;text-align:center">'
        '<div style="font-size:54px;color:#00ff88">✓</div>'
        '<h1 style="margin:10px 0">Seller verified</h1>'
        '<p style="color:#a8c0ba;line-height:1.6">Your Merco seller account is now active. Your store has been created successfully.</p>'
        '<a href="/login" style="display:inline-block;margin-top:12px;padding:13px 20px;border-radius:12px;background:#00ff88;color:#04100a;text-decoration:none;font-weight:700">Log in to your store</a>'
        '</main></body></html>'
    ), 200


try:
    app.add_url_rule('/seller-verification-success', endpoint='seller_verification_success', view_func=_seller_verification_success)
except AssertionError:
    pass

merco_runtime._activate_seller = _activate_seller_fixed
app.view_functions['verify_seller_whatsapp'] = _verify_seller_whatsapp_fixed
app.view_functions['activate_seller_production'] = _activate_seller_fixed
